name: r_environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base
  - r-dplyr
  - r-stringr
  - r-dendextend
  - r-phylogram
  - r-ggplot2
  - r-readr
  - r-ape
  - r-purrr
  - bioconductor-snprelate
  - bioconductor-seqarray
  - bioconductor-gdsfmt
  - bcftools