reference:            '/storage/aglebus/gbs/data/reference/ARS-UCD1.2_Btau5.0.1Y/ARS-UCD1.2_Btau5.0.1Y.fa'
faidx:                '/storage/aglebus/gbs/data/reference/ARS-UCD1.2_Btau5.0.1Y/faidx'
bwaidx:               '/storage/aglebus/gbs/data/reference/ARS-UCD1.2_Btau5.0.1Y/bwaidx'
reads:                '/storage/aglebus/gbs/data/reads/train_fastq'
ref_panel_vcf:        '/storage/aglebus/gbs/data/ref_panel/BGVD/*.vcf.gz'
ref_panel_index:      '/storage/aglebus/gbs/data/ref_panel/BGVD/*.vcf.gz.tbi'
ref_panel_tsv:        '/storage/aglebus/gbs/data/ref_panel/BGVD/*.tsv.gz'
ref_panel_tsv_index:  '/storage/aglebus/gbs/data/ref_panel/BGVD/*.tsv.gz.tbi'
downsample_rate:      '0.9'
bed:                  '/storage/aglebus/gbs/data/regions/SNV_53_converted_to_GCF_002263795.3_chr.bed'
outdir:               'results'
reports:              true
cpus:                 '96'
memory:               '2 TB'